spring.application.name=AquaSmart 

# DATABASE CONNECTION (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/aquasmart
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api

# SERVER PORT CONFIGURATION
server.port=8080